FROM python:3.11-slim

WORKDIR /mlops-project

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    gcc \
    git \ 
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN chmod -R 777 /mlops-project/logs

ENV PYTHONUNBUFFERED=1

#CMD ["sh", "-c", "python scripts/main.py all --model_name movie_predictor &&  tail -f /dev/null"] # 로깅 작업을 위해 잠시 살려둠
CMD ["sh", "-c", "python scripts/main.py all --model_name movie_predictor"]