version: '3.8' 
services:
  my-mlops-db:
    image: postgres:13
    container_name: my-mlops-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - my-mlops-network
    volumes:
      - db_data:/var/lib/postgresql/data

  my-mlops:
    build:
      context: ../../
      dockerfile: services/model_inference/dockerfile
      args:
        EXCLUDE_FRONTEND: "true"
    image: jkim1209/mlops-model:1.4.3
    env_file:
      - ../../.env # Warning error 때문에 추가
    container_name: my-mlops-model
    environment:
      DB_HOST: my-mlops-db
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: root
      DB_PORT: 5432
    networks:
      - my-mlops-network
    depends_on:
      - my-mlops-db
    volumes:  
      - ../../logs:/mlops-project/logs

networks:
  my-mlops-network:
    driver: bridge

volumes:
  db_data:
