version: '3.8'

services:
  my-mlops-api:
    build:
      context: ../../
      dockerfile: services/api/Dockerfile
      args:
        EXCLUDE_FRONTEND: "true"
    image: jkim1209/mlops-api:1.3.3
    container_name: my-mlops-api
    ports:
      - "8000:8000"
    env_file:
      - ../../.env
    environment:
      DB_HOST: my-mlops-db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: root
    networks:
      - my-mlops-network
    depends_on:
      my-mlops-db:
        condition: service_healthy
    volumes:  
      - ../../logs:/mlops-project/logs
    restart: always

  my-mlops-db:
    image: postgres:13
    container_name: my-mlops-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - my-mlops-network
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  my-mlops-network:
    external: true

volumes:
  db_data:
