version: '3.8'

services:
  mlops-api:
    build:
      context: ../../
      dockerfile: services/api/Dockerfile
    image: jkim1209/mlops-api:1.0.2
    container_name: mlops-api
    ports:
      - "8000:8000"
    env_file:
      - ../../.env
    environment:
      DB_HOST: my-mlops-db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: root
    networks:
      - my-mlops-network
    depends_on:
      - my-mlops-db

networks:
  my-mlops-network:
    external: true # 이미 model_inference에서 만든 네트워크를 재사용
