FROM python:3.11-slim

WORKDIR /mlops-project

# 필수 시스템 패키지 설치
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# requirements 설치
COPY ../../requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ../../ ./

# .dockerignore에서 제외된 폴더 중 필요한 폴더 명시
COPY ../../models ./models
COPY ../../data ./data

# FastAPI 실행
CMD ["uvicorn", "scripts.webapp:app", "--host", "0.0.0.0", "--port", "8000"]
